## ECBM E4040 Homework 4 - Programming Problem

In [1]:
from hw4_utils import load_data
train_set, valid_set, test_set, dicts = load_data()

WARNING (theano.sandbox.cuda): CUDA is installed, but device gpu is not available  (error: Unable to get the number of gpus available: no CUDA-capable device is detected)


### Problem a: Recurrent Neural Network
#### Bullet 1: Experiment with RNNSLU

**(1) Parameter Setting: win=3, emb_dimension=50** 

**Result: **
``` BEST RESULT: epoch 49 valid 96.9% best test 93.73% with the model.```

In [2]:
from hw4a import test_rnnslu
test_rnnslu(win=3, emb_dimension=50)

verbose: True
normal: True
win: 3
savemodel: False
fold: 3
seed: 345
emb_dimension: 50
nepochs: 60
nhidden: 200
decay: True
lr: 0.0970806646813
folder: ../result
... loading the dataset
... building the model
... training
NEW BEST: epoch 0 valid F1 68.15 best test F1 63.7
NEW BEST: epoch 1 valid F1 78.92 best test F1 74.97
NEW BEST: epoch 2 valid F1 82.06 best test F1 78.61
NEW BEST: epoch 3 valid F1 86.26 best test F1 82.81
NEW BEST: epoch 4 valid F1 88.28 best test F1 84.38
NEW BEST: epoch 5 valid F1 90.31 best test F1 86.4

NEW BEST: epoch 7 valid F1 91.04 best test F1 89.18
NEW BEST: epoch 8 valid F1 93.66 best test F1 90.45
NEW BEST: epoch 9 valid F1 94.42 best test F1 91.57

NEW BEST: epoch 11 valid F1 94.45 best test F1 92.29

NEW BEST: epoch 13 valid F1 95.72 best test F1 92.61

NEW BEST: epoch 15 valid F1 96.05 best test F1 93.07

NEW BEST: epoch 17 valid F1 96.26 best test F1 93.42
NEW BEST: epoch 18 valid F1 96.32 best test F1 93.69

NEW BEST: epoch 20 valid F1 96.34 best te

(<hw4_nn.RNNSLU at 0x7fc4f28ae710>,
 {'labels2idx': {'B-aircraft_code': 0,
   'B-airline_code': 1,
   'B-airline_name': 2,
   'B-airport_code': 3,
   'B-airport_name': 4,
   'B-arrive_date.date_relative': 5,
   'B-arrive_date.day_name': 6,
   'B-arrive_date.day_number': 7,
   'B-arrive_date.month_name': 8,
   'B-arrive_date.today_relative': 9,
   'B-arrive_time.end_time': 10,
   'B-arrive_time.period_mod': 11,
   'B-arrive_time.period_of_day': 12,
   'B-arrive_time.start_time': 13,
   'B-arrive_time.time': 14,
   'B-arrive_time.time_relative': 15,
   'B-booking_class': 16,
   'B-city_name': 17,
   'B-class_type': 18,
   'B-compartment': 19,
   'B-connect': 20,
   'B-cost_relative': 21,
   'B-day_name': 22,
   'B-day_number': 23,
   'B-days_code': 24,
   'B-depart_date.date_relative': 25,
   'B-depart_date.day_name': 26,
   'B-depart_date.day_number': 27,
   'B-depart_date.month_name': 28,
   'B-depart_date.today_relative': 29,
   'B-depart_date.year': 30,
   'B-depart_time.end_time': 3

**(2) Parameter Setting: win=5, emb_dimension=50** 

**Result: **
```BEST RESULT: epoch 57 valid 96.96% best test 93.57% with the model.```

In [3]:
from hw4a import test_rnnslu
test_rnnslu(win=5, emb_dimension=50)

verbose: True
normal: True
win: 5
savemodel: False
fold: 3
seed: 345
emb_dimension: 50
nepochs: 60
nhidden: 200
decay: True
lr: 0.0970806646813
folder: ../result
... loading the dataset
... building the model
... training
NEW BEST: epoch 0 valid F1 69.47 best test F1 65.79
NEW BEST: epoch 1 valid F1 80.18 best test F1 76.07
NEW BEST: epoch 2 valid F1 82.58 best test F1 79.6
NEW BEST: epoch 3 valid F1 87.23 best test F1 83.35
NEW BEST: epoch 4 valid F1 89.3 best test F1 85.58
NEW BEST: epoch 5 valid F1 90.55 best test F1 87.2

NEW BEST: epoch 7 valid F1 91.56 best test F1 89.85
NEW BEST: epoch 8 valid F1 93.18 best test F1 91.09
NEW BEST: epoch 9 valid F1 93.7 best test F1 91.58
NEW BEST: epoch 10 valid F1 94.3 best test F1 91.64

NEW BEST: epoch 12 valid F1 94.86 best test F1 92.29
NEW BEST: epoch 13 valid F1 94.87 best test F1 92.42
NEW BEST: epoch 14 valid F1 95.4 best test F1 92.36


NEW BEST: epoch 17 valid F1 95.91 best test F1 93.41
NEW BEST: epoch 18 valid F1 95.96 best test F1 

(<hw4_nn.RNNSLU at 0x7fc4f40a96d0>,
 {'labels2idx': {'B-aircraft_code': 0,
   'B-airline_code': 1,
   'B-airline_name': 2,
   'B-airport_code': 3,
   'B-airport_name': 4,
   'B-arrive_date.date_relative': 5,
   'B-arrive_date.day_name': 6,
   'B-arrive_date.day_number': 7,
   'B-arrive_date.month_name': 8,
   'B-arrive_date.today_relative': 9,
   'B-arrive_time.end_time': 10,
   'B-arrive_time.period_mod': 11,
   'B-arrive_time.period_of_day': 12,
   'B-arrive_time.start_time': 13,
   'B-arrive_time.time': 14,
   'B-arrive_time.time_relative': 15,
   'B-booking_class': 16,
   'B-city_name': 17,
   'B-class_type': 18,
   'B-compartment': 19,
   'B-connect': 20,
   'B-cost_relative': 21,
   'B-day_name': 22,
   'B-day_number': 23,
   'B-days_code': 24,
   'B-depart_date.date_relative': 25,
   'B-depart_date.day_name': 26,
   'B-depart_date.day_number': 27,
   'B-depart_date.month_name': 28,
   'B-depart_date.today_relative': 29,
   'B-depart_date.year': 30,
   'B-depart_time.end_time': 3

**(3) Parameter Setting: win=7, emb_dimension=50** 

**Result:**
```BEST RESULT: epoch 57 valid 97.23% best test 94.2% with the model.```

In [1]:
from hw4a import test_rnnslu
test_rnnslu(win=7, emb_dimension=50)

WARNING (theano.sandbox.cuda): CUDA is installed, but device gpu is not available  (error: Unable to get the number of gpus available: no CUDA-capable device is detected)


verbose: True
normal: True
win: 7
savemodel: False
fold: 3
seed: 345
emb_dimension: 50
nepochs: 60
nhidden: 200
decay: True
lr: 0.0970806646813
folder: ../result
... loading the dataset
... building the model
... training
NEW BEST: epoch 0 valid F1 68.18 best test F1 66.22
NEW BEST: epoch 1 valid F1 80.63 best test F1 77.98
NEW BEST: epoch 2 valid F1 83.79 best test F1 80.66
NEW BEST: epoch 3 valid F1 88.42 best test F1 84.92
NEW BEST: epoch 4 valid F1 89.65 best test F1 85.97
NEW BEST: epoch 5 valid F1 91.02 best test F1 86.87
NEW BEST: epoch 6 valid F1 91.45 best test F1 88.81
NEW BEST: epoch 7 valid F1 92.05 best test F1 89.89
NEW BEST: epoch 8 valid F1 93.78 best test F1 90.69
NEW BEST: epoch 9 valid F1 94.19 best test F1 91.27
NEW BEST: epoch 10 valid F1 94.7 best test F1 91.64
NEW BEST: epoch 11 valid F1 94.88 best test F1 92.23
NEW BEST: epoch 12 valid F1 95.4 best test F1 92.73
NEW BEST: epoch 13 valid F1 95.45 best test F1 92.79

NEW BEST: epoch 15 valid F1 95.55 best test F1 

/home/ubuntu/miniconda2/envs/theano/lib/python2.7/site-packages/theano/tensor/signal/downsample.py:6: UserWarning: downsample module has been moved to the theano.tensor.signal.pool module.
  "downsample module has been moved to the theano.tensor.signal.pool module.")


(<hw4_nn.RNNSLU at 0x7f4b51404c50>,
 {'labels2idx': {'B-aircraft_code': 0,
   'B-airline_code': 1,
   'B-airline_name': 2,
   'B-airport_code': 3,
   'B-airport_name': 4,
   'B-arrive_date.date_relative': 5,
   'B-arrive_date.day_name': 6,
   'B-arrive_date.day_number': 7,
   'B-arrive_date.month_name': 8,
   'B-arrive_date.today_relative': 9,
   'B-arrive_time.end_time': 10,
   'B-arrive_time.period_mod': 11,
   'B-arrive_time.period_of_day': 12,
   'B-arrive_time.start_time': 13,
   'B-arrive_time.time': 14,
   'B-arrive_time.time_relative': 15,
   'B-booking_class': 16,
   'B-city_name': 17,
   'B-class_type': 18,
   'B-compartment': 19,
   'B-connect': 20,
   'B-cost_relative': 21,
   'B-day_name': 22,
   'B-day_number': 23,
   'B-days_code': 24,
   'B-depart_date.date_relative': 25,
   'B-depart_date.day_name': 26,
   'B-depart_date.day_number': 27,
   'B-depart_date.month_name': 28,
   'B-depart_date.today_relative': 29,
   'B-depart_date.year': 30,
   'B-depart_time.end_time': 3

**(4) Parameter Setting: win=9, emb_dimension=50** 

**Result:**
```BEST RESULT: epoch 43 valid 96.61% best test 94.2% with the model.```

In [4]:
from hw4a import test_rnnslu
test_rnnslu(win=9, emb_dimension=50)

verbose: True
normal: True
win: 9
savemodel: False
fold: 3
seed: 345
emb_dimension: 50
nepochs: 60
nhidden: 200
decay: True
lr: 0.0970806646813
folder: ../result
... loading the dataset
... building the model
... training
NEW BEST: epoch 0 valid F1 68.26 best test F1 65.92
NEW BEST: epoch 1 valid F1 79.48 best test F1 76.32
NEW BEST: epoch 2 valid F1 82.83 best test F1 79.74
NEW BEST: epoch 3 valid F1 87.41 best test F1 83.23
NEW BEST: epoch 4 valid F1 89.39 best test F1 85.41
NEW BEST: epoch 5 valid F1 90.61 best test F1 87.16
NEW BEST: epoch 6 valid F1 91.24 best test F1 88.87
NEW BEST: epoch 7 valid F1 92.62 best test F1 89.99
NEW BEST: epoch 8 valid F1 93.7 best test F1 90.95
NEW BEST: epoch 9 valid F1 94.41 best test F1 91.29
NEW BEST: epoch 10 valid F1 94.66 best test F1 91.1
NEW BEST: epoch 11 valid F1 95.0 best test F1 92.47
NEW BEST: epoch 12 valid F1 95.25 best test F1 92.55
NEW BEST: epoch 13 valid F1 95.53 best test F1 92.65

NEW BEST: epoch 15 valid F1 96.02 best test F1 9

(<hw4_nn.RNNSLU at 0x7fc4f386a8d0>,
 {'labels2idx': {'B-aircraft_code': 0,
   'B-airline_code': 1,
   'B-airline_name': 2,
   'B-airport_code': 3,
   'B-airport_name': 4,
   'B-arrive_date.date_relative': 5,
   'B-arrive_date.day_name': 6,
   'B-arrive_date.day_number': 7,
   'B-arrive_date.month_name': 8,
   'B-arrive_date.today_relative': 9,
   'B-arrive_time.end_time': 10,
   'B-arrive_time.period_mod': 11,
   'B-arrive_time.period_of_day': 12,
   'B-arrive_time.start_time': 13,
   'B-arrive_time.time': 14,
   'B-arrive_time.time_relative': 15,
   'B-booking_class': 16,
   'B-city_name': 17,
   'B-class_type': 18,
   'B-compartment': 19,
   'B-connect': 20,
   'B-cost_relative': 21,
   'B-day_name': 22,
   'B-day_number': 23,
   'B-days_code': 24,
   'B-depart_date.date_relative': 25,
   'B-depart_date.day_name': 26,
   'B-depart_date.day_number': 27,
   'B-depart_date.month_name': 28,
   'B-depart_date.today_relative': 29,
   'B-depart_date.year': 30,
   'B-depart_time.end_time': 3

**(5) Parameter Setting: win=15, emb_dimension=50** 

**Result: **
```BEST RESULT: epoch 44 valid 96.99% best test 93.67% with the model.```

In [1]:
from hw4a import test_rnnslu
test_rnnslu(win=15, emb_dimension=50)

Using gpu device 0: GRID K520 (CNMeM is disabled, cuDNN Version is too old. Update to v5, was 3007.)
/home/ubuntu/miniconda2/envs/theano/lib/python2.7/site-packages/theano/tensor/signal/downsample.py:6: UserWarning: downsample module has been moved to the theano.tensor.signal.pool module.
  "downsample module has been moved to the theano.tensor.signal.pool module.")


verbose: True
normal: True
win: 15
savemodel: False
fold: 3
seed: 345
emb_dimension: 50
nepochs: 60
nhidden: 200
decay: True
lr: 0.0970806646813
folder: ../result
... loading the dataset
... building the model
... training
NEW BEST: epoch 0 valid F1 68.29 best test F1 63.82
NEW BEST: epoch 1 valid F1 79.15 best test F1 75.49
NEW BEST: epoch 2 valid F1 83.02 best test F1 80.2
NEW BEST: epoch 3 valid F1 87.79 best test F1 84.59
NEW BEST: epoch 4 valid F1 89.25 best test F1 86.15
NEW BEST: epoch 5 valid F1 90.8 best test F1 86.46
NEW BEST: epoch 6 valid F1 91.94 best test F1 88.94
NEW BEST: epoch 7 valid F1 93.15 best test F1 90.05
NEW BEST: epoch 8 valid F1 94.05 best test F1 90.95
NEW BEST: epoch 9 valid F1 94.58 best test F1 90.95
NEW BEST: epoch 10 valid F1 95.31 best test F1 91.48

NEW BEST: epoch 12 valid F1 95.58 best test F1 92.96
NEW BEST: epoch 13 valid F1 95.76 best test F1 92.47
NEW BEST: epoch 14 valid F1 96.19 best test F1 93.01


NEW BEST: epoch 17 valid F1 96.48 best test 

(<hw4_nn.RNNSLU at 0x7fc560173c50>,
 {'labels2idx': {'B-aircraft_code': 0,
   'B-airline_code': 1,
   'B-airline_name': 2,
   'B-airport_code': 3,
   'B-airport_name': 4,
   'B-arrive_date.date_relative': 5,
   'B-arrive_date.day_name': 6,
   'B-arrive_date.day_number': 7,
   'B-arrive_date.month_name': 8,
   'B-arrive_date.today_relative': 9,
   'B-arrive_time.end_time': 10,
   'B-arrive_time.period_mod': 11,
   'B-arrive_time.period_of_day': 12,
   'B-arrive_time.start_time': 13,
   'B-arrive_time.time': 14,
   'B-arrive_time.time_relative': 15,
   'B-booking_class': 16,
   'B-city_name': 17,
   'B-class_type': 18,
   'B-compartment': 19,
   'B-connect': 20,
   'B-cost_relative': 21,
   'B-day_name': 22,
   'B-day_number': 23,
   'B-days_code': 24,
   'B-depart_date.date_relative': 25,
   'B-depart_date.day_name': 26,
   'B-depart_date.day_number': 27,
   'B-depart_date.month_name': 28,
   'B-depart_date.today_relative': 29,
   'B-depart_date.year': 30,
   'B-depart_time.end_time': 3

**(6) Parameter Setting: win=7, emb_dimension=40** 

**Result: **
```BEST RESULT: epoch 47 valid 97.19% best test 93.84% with the model.```

In [5]:
from hw4a import test_rnnslu
test_rnnslu(win=7, emb_dimension=40)

verbose: True
normal: True
win: 7
savemodel: False
fold: 3
seed: 345
emb_dimension: 40
nepochs: 60
nhidden: 200
decay: True
lr: 0.0970806646813
folder: ../result
... loading the dataset
... building the model
... training
NEW BEST: epoch 0 valid F1 68.79 best test F1 65.74
NEW BEST: epoch 1 valid F1 79.78 best test F1 76.83
NEW BEST: epoch 2 valid F1 83.61 best test F1 81.2
NEW BEST: epoch 3 valid F1 88.36 best test F1 84.91
NEW BEST: epoch 4 valid F1 89.15 best test F1 85.49
NEW BEST: epoch 5 valid F1 91.02 best test F1 87.38
NEW BEST: epoch 6 valid F1 91.55 best test F1 88.78
NEW BEST: epoch 7 valid F1 92.01 best test F1 89.92
NEW BEST: epoch 8 valid F1 94.0 best test F1 91.07
NEW BEST: epoch 9 valid F1 94.22 best test F1 91.28
NEW BEST: epoch 10 valid F1 94.26 best test F1 91.59
NEW BEST: epoch 11 valid F1 94.51 best test F1 92.16
NEW BEST: epoch 12 valid F1 95.0 best test F1 92.28
NEW BEST: epoch 13 valid F1 95.22 best test F1 92.3

NEW BEST: epoch 15 valid F1 95.52 best test F1 92

(<hw4_nn.RNNSLU at 0x7fc4f4c46690>,
 {'labels2idx': {'B-aircraft_code': 0,
   'B-airline_code': 1,
   'B-airline_name': 2,
   'B-airport_code': 3,
   'B-airport_name': 4,
   'B-arrive_date.date_relative': 5,
   'B-arrive_date.day_name': 6,
   'B-arrive_date.day_number': 7,
   'B-arrive_date.month_name': 8,
   'B-arrive_date.today_relative': 9,
   'B-arrive_time.end_time': 10,
   'B-arrive_time.period_mod': 11,
   'B-arrive_time.period_of_day': 12,
   'B-arrive_time.start_time': 13,
   'B-arrive_time.time': 14,
   'B-arrive_time.time_relative': 15,
   'B-booking_class': 16,
   'B-city_name': 17,
   'B-class_type': 18,
   'B-compartment': 19,
   'B-connect': 20,
   'B-cost_relative': 21,
   'B-day_name': 22,
   'B-day_number': 23,
   'B-days_code': 24,
   'B-depart_date.date_relative': 25,
   'B-depart_date.day_name': 26,
   'B-depart_date.day_number': 27,
   'B-depart_date.month_name': 28,
   'B-depart_date.today_relative': 29,
   'B-depart_date.year': 30,
   'B-depart_time.end_time': 3

**(7) Parameter Setting: win=7, emb_dimension=60** 

**Result: **
```BEST RESULT: epoch 59 valid 97.37% best test 94.15% with the model.```

In [6]:
from hw4a import test_rnnslu
test_rnnslu(win=7, emb_dimension=60)

verbose: True
normal: True
win: 7
savemodel: False
fold: 3
seed: 345
emb_dimension: 60
nepochs: 60
nhidden: 200
decay: True
lr: 0.0970806646813
folder: ../result
... loading the dataset
... building the model
... training
NEW BEST: epoch 0 valid F1 69.88 best test F1 66.59
NEW BEST: epoch 1 valid F1 80.07 best test F1 76.67
NEW BEST: epoch 2 valid F1 83.76 best test F1 81.69
NEW BEST: epoch 3 valid F1 87.96 best test F1 84.94
NEW BEST: epoch 4 valid F1 89.23 best test F1 85.82
NEW BEST: epoch 5 valid F1 91.17 best test F1 87.61
NEW BEST: epoch 6 valid F1 91.57 best test F1 89.37
NEW BEST: epoch 7 valid F1 92.97 best test F1 90.54
NEW BEST: epoch 8 valid F1 93.81 best test F1 91.68
NEW BEST: epoch 9 valid F1 94.05 best test F1 91.99
NEW BEST: epoch 10 valid F1 94.4 best test F1 91.98
NEW BEST: epoch 11 valid F1 95.01 best test F1 92.32
NEW BEST: epoch 12 valid F1 95.72 best test F1 92.9

NEW BEST: epoch 14 valid F1 95.89 best test F1 92.59


NEW BEST: epoch 17 valid F1 96.16 best test F

(<hw4_nn.RNNSLU at 0x7fc4ef455510>,
 {'labels2idx': {'B-aircraft_code': 0,
   'B-airline_code': 1,
   'B-airline_name': 2,
   'B-airport_code': 3,
   'B-airport_name': 4,
   'B-arrive_date.date_relative': 5,
   'B-arrive_date.day_name': 6,
   'B-arrive_date.day_number': 7,
   'B-arrive_date.month_name': 8,
   'B-arrive_date.today_relative': 9,
   'B-arrive_time.end_time': 10,
   'B-arrive_time.period_mod': 11,
   'B-arrive_time.period_of_day': 12,
   'B-arrive_time.start_time': 13,
   'B-arrive_time.time': 14,
   'B-arrive_time.time_relative': 15,
   'B-booking_class': 16,
   'B-city_name': 17,
   'B-class_type': 18,
   'B-compartment': 19,
   'B-connect': 20,
   'B-cost_relative': 21,
   'B-day_name': 22,
   'B-day_number': 23,
   'B-days_code': 24,
   'B-depart_date.date_relative': 25,
   'B-depart_date.day_name': 26,
   'B-depart_date.day_number': 27,
   'B-depart_date.month_name': 28,
   'B-depart_date.today_relative': 29,
   'B-depart_date.year': 30,
   'B-depart_time.end_time': 3

From above experiments, we can find that test accracy reached biggest when ```win=7``` or ```emb_dimension=50```. The accracy droped down at other parameter settings.

Overall, the best parameter setting is **win=7, emb_dimension=50**. 
The **Best Result** obtained at ```epoch 57``` with validation accracy of ```97.23%``` and best test accracy of ```94.2%```. We can find that RNN has great performance in this task.

#### Bullet 2: Experiment with RNNSLU without normalizing word embeddings

In [7]:
from hw4a import test_rnnslu
test_rnnslu(win=7, emb_dimension=50, normal=False)

verbose: True
normal: False
win: 7
savemodel: False
fold: 3
seed: 345
emb_dimension: 50
nepochs: 60
nhidden: 200
decay: True
lr: 0.0970806646813
folder: ../result
... loading the dataset
... building the model
... training
NEW BEST: epoch 0 valid F1 68.96 best test F1 63.35
NEW BEST: epoch 1 valid F1 81.28 best test F1 76.9
NEW BEST: epoch 2 valid F1 84.73 best test F1 81.46
NEW BEST: epoch 3 valid F1 88.04 best test F1 84.06
NEW BEST: epoch 4 valid F1 90.05 best test F1 86.02
NEW BEST: epoch 5 valid F1 91.31 best test F1 86.93
NEW BEST: epoch 6 valid F1 92.65 best test F1 88.75
NEW BEST: epoch 7 valid F1 93.21 best test F1 89.79
NEW BEST: epoch 8 valid F1 94.0 best test F1 90.6
NEW BEST: epoch 9 valid F1 94.86 best test F1 90.68
NEW BEST: epoch 10 valid F1 95.13 best test F1 91.98

NEW BEST: epoch 12 valid F1 95.68 best test F1 92.92
NEW BEST: epoch 13 valid F1 95.91 best test F1 92.79

NEW BEST: epoch 15 valid F1 96.25 best test F1 93.48
NEW BEST: epoch 16 valid F1 96.33 best test F1

(<hw4_nn.RNNSLU at 0x7fc4ebf46250>,
 {'labels2idx': {'B-aircraft_code': 0,
   'B-airline_code': 1,
   'B-airline_name': 2,
   'B-airport_code': 3,
   'B-airport_name': 4,
   'B-arrive_date.date_relative': 5,
   'B-arrive_date.day_name': 6,
   'B-arrive_date.day_number': 7,
   'B-arrive_date.month_name': 8,
   'B-arrive_date.today_relative': 9,
   'B-arrive_time.end_time': 10,
   'B-arrive_time.period_mod': 11,
   'B-arrive_time.period_of_day': 12,
   'B-arrive_time.start_time': 13,
   'B-arrive_time.time': 14,
   'B-arrive_time.time_relative': 15,
   'B-booking_class': 16,
   'B-city_name': 17,
   'B-class_type': 18,
   'B-compartment': 19,
   'B-connect': 20,
   'B-cost_relative': 21,
   'B-day_name': 22,
   'B-day_number': 23,
   'B-days_code': 24,
   'B-depart_date.date_relative': 25,
   'B-depart_date.day_name': 26,
   'B-depart_date.day_number': 27,
   'B-depart_date.month_name': 28,
   'B-depart_date.today_relative': 29,
   'B-depart_date.year': 30,
   'B-depart_time.end_time': 3

```BEST RESULT: epoch 31 valid 97.56% best test 94.0% with the model.```

We can see that the validation accracy without normalization is higher than with normalization, however, test accracy is opposite. So there may have over-fitting without normalization. Therefore, normalizing word embeddings can improve the RNN performance of testing in this task.

#### Bullet 3: Implement RNN with two hidden layers

In [1]:
from hw4a import test_rnnslu2
test_rnnslu2(win=7, emb_dimension=50)

Using gpu device 0: GRID K520 (CNMeM is disabled, cuDNN Version is too old. Update to v5, was 3007.)
/home/ubuntu/miniconda2/envs/theano/lib/python2.7/site-packages/theano/tensor/signal/downsample.py:6: UserWarning: downsample module has been moved to the theano.tensor.signal.pool module.
  "downsample module has been moved to the theano.tensor.signal.pool module.")


verbose: True
nhidden2: 100
win: 7
nhidden1: 200
savemodel: False
fold: 3
seed: 345
emb_dimension: 50
nepochs: 60
decay: True
lr: 0.0970806646813
folder: ../result
... loading the dataset
... building the model
... training
NEW BEST: epoch 0 valid F1 58.75 best test F1 54.23
NEW BEST: epoch 1 valid F1 69.76 best test F1 64.41
NEW BEST: epoch 2 valid F1 75.41 best test F1 73.81
NEW BEST: epoch 3 valid F1 81.08 best test F1 77.97
NEW BEST: epoch 4 valid F1 84.62 best test F1 81.3
NEW BEST: epoch 5 valid F1 86.64 best test F1 83.17
NEW BEST: epoch 6 valid F1 87.97 best test F1 84.26
NEW BEST: epoch 7 valid F1 90.93 best test F1 87.33

NEW BEST: epoch 9 valid F1 91.02 best test F1 87.54
NEW BEST: epoch 10 valid F1 92.05 best test F1 88.9
NEW BEST: epoch 11 valid F1 92.65 best test F1 89.74
NEW BEST: epoch 12 valid F1 92.69 best test F1 90.06
NEW BEST: epoch 13 valid F1 93.76 best test F1 90.57
NEW BEST: epoch 14 valid F1 94.06 best test F1 90.23

NEW BEST: epoch 16 valid F1 94.1 best test 

```BEST RESULT: epoch 49 valid 96.68% best test 92.61% with the model.```

RNN with two hidden layers should have better performance than the RNN with single layer, but the result seems different. Better result may obtain after more epoches. Or, the parameters should be reset to get a better result. However, the accuracy may not decrease in the future iterations after reviewing the trend of accuracy goes.

#### Bullet 4: Experiment with layer normalization

I chose 5 typical parameter settings in part I and did the experiments below.

**(1) Parameter Setting: win=7, emb_dimension=50** 

**Result: **
    ```BEST RESULT: epoch 23 valid 96.8% best test 94.16% with the model.```

In [1]:
from hw4a import test_rnnslu_norm
test_rnnslu_norm(win=7, emb_dimension=50)

Using gpu device 0: GRID K520 (CNMeM is disabled, cuDNN Version is too old. Update to v5, was 3007.)
/home/ubuntu/miniconda2/envs/theano/lib/python2.7/site-packages/theano/tensor/signal/downsample.py:6: UserWarning: downsample module has been moved to the theano.tensor.signal.pool module.
  "downsample module has been moved to the theano.tensor.signal.pool module.")


verbose: True
normal: True
win: 7
savemodel: False
fold: 3
seed: 345
emb_dimension: 50
nepochs: 60
nhidden: 200
decay: True
lr: 0.0970806646813
folder: ../result
... loading the dataset
... building the model
... training
NEW BEST: epoch 0 valid F1 83.63 best test F1 79.71
NEW BEST: epoch 1 valid F1 87.52 best test F1 84.37
NEW BEST: epoch 2 valid F1 91.9 best test F1 88.23
NEW BEST: epoch 3 valid F1 92.88 best test F1 89.83
NEW BEST: epoch 4 valid F1 92.98 best test F1 89.37
NEW BEST: epoch 5 valid F1 94.64 best test F1 91.88

NEW BEST: epoch 7 valid F1 95.31 best test F1 92.46
NEW BEST: epoch 8 valid F1 96.01 best test F1 93.38

NEW BEST: epoch 10 valid F1 96.06 best test F1 92.9
NEW BEST: epoch 11 valid F1 96.24 best test F1 93.39
NEW BEST: epoch 12 valid F1 96.65 best test F1 93.81




NEW BEST: epoch 17 valid F1 96.71 best test F1 93.86



NEW BEST: epoch 21 valid F1 96.72 best test F1 93.78
NEW BEST: epoch 22 valid F1 96.77 best test F1 93.98
NEW BEST: epoch 23 valid F1 96.8 best

(<hw4_nn.RNNSLU_norm at 0x7fee54652a10>,
 {'labels2idx': {'B-aircraft_code': 0,
   'B-airline_code': 1,
   'B-airline_name': 2,
   'B-airport_code': 3,
   'B-airport_name': 4,
   'B-arrive_date.date_relative': 5,
   'B-arrive_date.day_name': 6,
   'B-arrive_date.day_number': 7,
   'B-arrive_date.month_name': 8,
   'B-arrive_date.today_relative': 9,
   'B-arrive_time.end_time': 10,
   'B-arrive_time.period_mod': 11,
   'B-arrive_time.period_of_day': 12,
   'B-arrive_time.start_time': 13,
   'B-arrive_time.time': 14,
   'B-arrive_time.time_relative': 15,
   'B-booking_class': 16,
   'B-city_name': 17,
   'B-class_type': 18,
   'B-compartment': 19,
   'B-connect': 20,
   'B-cost_relative': 21,
   'B-day_name': 22,
   'B-day_number': 23,
   'B-days_code': 24,
   'B-depart_date.date_relative': 25,
   'B-depart_date.day_name': 26,
   'B-depart_date.day_number': 27,
   'B-depart_date.month_name': 28,
   'B-depart_date.today_relative': 29,
   'B-depart_date.year': 30,
   'B-depart_time.end_tim

**(2) Parameter Setting: win=5, emb_dimension=50** 

**Result: **
```BEST RESULT: epoch 34 valid 96.81% best test 94.35% with the model.```

In [2]:
from hw4a import test_rnnslu_norm
test_rnnslu_norm(win=5, emb_dimension=50)

verbose: True
normal: True
win: 5
savemodel: False
fold: 3
seed: 345
emb_dimension: 50
nepochs: 60
nhidden: 200
decay: True
lr: 0.0970806646813
folder: ../result
... loading the dataset
... building the model
... training
NEW BEST: epoch 0 valid F1 84.2 best test F1 80.36
NEW BEST: epoch 1 valid F1 88.19 best test F1 84.16
NEW BEST: epoch 2 valid F1 91.76 best test F1 89.28
NEW BEST: epoch 3 valid F1 93.32 best test F1 90.65
NEW BEST: epoch 4 valid F1 93.66 best test F1 90.42
NEW BEST: epoch 5 valid F1 94.71 best test F1 91.78

NEW BEST: epoch 7 valid F1 95.46 best test F1 92.81
NEW BEST: epoch 8 valid F1 95.48 best test F1 92.78
NEW BEST: epoch 9 valid F1 96.1 best test F1 93.6


NEW BEST: epoch 12 valid F1 96.57 best test F1 93.51


NEW BEST: epoch 15 valid F1 96.6 best test F1 93.74







NEW BEST: epoch 23 valid F1 96.73 best test F1 94.27










NEW BEST: epoch 34 valid F1 96.81 best test F1 94.35






















BEST RESULT: epoch 34 valid F1 96.81 best test F1 94.35 wi

(<hw4_nn.RNNSLU_norm at 0x7fedd765e310>,
 {'labels2idx': {'B-aircraft_code': 0,
   'B-airline_code': 1,
   'B-airline_name': 2,
   'B-airport_code': 3,
   'B-airport_name': 4,
   'B-arrive_date.date_relative': 5,
   'B-arrive_date.day_name': 6,
   'B-arrive_date.day_number': 7,
   'B-arrive_date.month_name': 8,
   'B-arrive_date.today_relative': 9,
   'B-arrive_time.end_time': 10,
   'B-arrive_time.period_mod': 11,
   'B-arrive_time.period_of_day': 12,
   'B-arrive_time.start_time': 13,
   'B-arrive_time.time': 14,
   'B-arrive_time.time_relative': 15,
   'B-booking_class': 16,
   'B-city_name': 17,
   'B-class_type': 18,
   'B-compartment': 19,
   'B-connect': 20,
   'B-cost_relative': 21,
   'B-day_name': 22,
   'B-day_number': 23,
   'B-days_code': 24,
   'B-depart_date.date_relative': 25,
   'B-depart_date.day_name': 26,
   'B-depart_date.day_number': 27,
   'B-depart_date.month_name': 28,
   'B-depart_date.today_relative': 29,
   'B-depart_date.year': 30,
   'B-depart_time.end_tim

**(3) Parameter Setting: win=9, emb_dimension=50** 

**Result: **
```BEST RESULT: epoch 28 valid 96.92% best test 94.09% with the model.```

In [3]:
from hw4a import test_rnnslu_norm
test_rnnslu_norm(win=9, emb_dimension=50)

verbose: True
normal: True
win: 9
savemodel: False
fold: 3
seed: 345
emb_dimension: 50
nepochs: 60
nhidden: 200
decay: True
lr: 0.0970806646813
folder: ../result
... loading the dataset
... building the model
... training
NEW BEST: epoch 0 valid F1 82.51 best test F1 78.9
NEW BEST: epoch 1 valid F1 86.68 best test F1 83.23
NEW BEST: epoch 2 valid F1 91.54 best test F1 87.39
NEW BEST: epoch 3 valid F1 93.11 best test F1 89.94
NEW BEST: epoch 4 valid F1 94.01 best test F1 89.69
NEW BEST: epoch 5 valid F1 95.02 best test F1 92.2

NEW BEST: epoch 7 valid F1 95.94 best test F1 93.53

NEW BEST: epoch 9 valid F1 95.96 best test F1 93.64
NEW BEST: epoch 10 valid F1 96.18 best test F1 93.24
NEW BEST: epoch 11 valid F1 96.23 best test F1 93.75
NEW BEST: epoch 12 valid F1 96.53 best test F1 93.92


NEW BEST: epoch 15 valid F1 96.71 best test F1 93.77





NEW BEST: epoch 21 valid F1 96.8 best test F1 93.89






NEW BEST: epoch 28 valid F1 96.92 best test F1 94.09























BEST RESU

(<hw4_nn.RNNSLU_norm at 0x7feddaa15190>,
 {'labels2idx': {'B-aircraft_code': 0,
   'B-airline_code': 1,
   'B-airline_name': 2,
   'B-airport_code': 3,
   'B-airport_name': 4,
   'B-arrive_date.date_relative': 5,
   'B-arrive_date.day_name': 6,
   'B-arrive_date.day_number': 7,
   'B-arrive_date.month_name': 8,
   'B-arrive_date.today_relative': 9,
   'B-arrive_time.end_time': 10,
   'B-arrive_time.period_mod': 11,
   'B-arrive_time.period_of_day': 12,
   'B-arrive_time.start_time': 13,
   'B-arrive_time.time': 14,
   'B-arrive_time.time_relative': 15,
   'B-booking_class': 16,
   'B-city_name': 17,
   'B-class_type': 18,
   'B-compartment': 19,
   'B-connect': 20,
   'B-cost_relative': 21,
   'B-day_name': 22,
   'B-day_number': 23,
   'B-days_code': 24,
   'B-depart_date.date_relative': 25,
   'B-depart_date.day_name': 26,
   'B-depart_date.day_number': 27,
   'B-depart_date.month_name': 28,
   'B-depart_date.today_relative': 29,
   'B-depart_date.year': 30,
   'B-depart_time.end_tim

**(4) Parameter Setting: win=7, emb_dimension=40** 

**Result: **
```BEST RESULT: epoch 32 valid 96.59% best test 93.82% with the model.```

In [4]:
from hw4a import test_rnnslu_norm
test_rnnslu_norm(win=7, emb_dimension=40)

verbose: True
normal: True
win: 7
savemodel: False
fold: 3
seed: 345
emb_dimension: 40
nepochs: 60
nhidden: 200
decay: True
lr: 0.0970806646813
folder: ../result
... loading the dataset
... building the model
... training
NEW BEST: epoch 0 valid F1 82.84 best test F1 79.23
NEW BEST: epoch 1 valid F1 86.05 best test F1 83.02
NEW BEST: epoch 2 valid F1 90.7 best test F1 87.73
NEW BEST: epoch 3 valid F1 91.84 best test F1 88.8
NEW BEST: epoch 4 valid F1 92.82 best test F1 88.86
NEW BEST: epoch 5 valid F1 93.65 best test F1 91.02

NEW BEST: epoch 7 valid F1 94.48 best test F1 92.48
NEW BEST: epoch 8 valid F1 94.95 best test F1 92.78
NEW BEST: epoch 9 valid F1 95.19 best test F1 92.95
NEW BEST: epoch 10 valid F1 95.36 best test F1 93.03
NEW BEST: epoch 11 valid F1 95.66 best test F1 93.67
NEW BEST: epoch 12 valid F1 95.74 best test F1 93.56
NEW BEST: epoch 13 valid F1 95.96 best test F1 93.65
NEW BEST: epoch 14 valid F1 96.05 best test F1 93.67
NEW BEST: epoch 15 valid F1 96.06 best test F1

(<hw4_nn.RNNSLU_norm at 0x7f35079eb0d0>,
 {'labels2idx': {'B-aircraft_code': 0,
   'B-airline_code': 1,
   'B-airline_name': 2,
   'B-airport_code': 3,
   'B-airport_name': 4,
   'B-arrive_date.date_relative': 5,
   'B-arrive_date.day_name': 6,
   'B-arrive_date.day_number': 7,
   'B-arrive_date.month_name': 8,
   'B-arrive_date.today_relative': 9,
   'B-arrive_time.end_time': 10,
   'B-arrive_time.period_mod': 11,
   'B-arrive_time.period_of_day': 12,
   'B-arrive_time.start_time': 13,
   'B-arrive_time.time': 14,
   'B-arrive_time.time_relative': 15,
   'B-booking_class': 16,
   'B-city_name': 17,
   'B-class_type': 18,
   'B-compartment': 19,
   'B-connect': 20,
   'B-cost_relative': 21,
   'B-day_name': 22,
   'B-day_number': 23,
   'B-days_code': 24,
   'B-depart_date.date_relative': 25,
   'B-depart_date.day_name': 26,
   'B-depart_date.day_number': 27,
   'B-depart_date.month_name': 28,
   'B-depart_date.today_relative': 29,
   'B-depart_date.year': 30,
   'B-depart_time.end_tim

**(5) Parameter Setting: win=7, emb_dimension=60** 

**Result: **
```BEST RESULT: epoch 38 valid 97.01% best test 94.02% with the model.```

In [5]:
from hw4a import test_rnnslu_norm
test_rnnslu_norm(win=7, emb_dimension=60)

verbose: True
normal: True
win: 7
savemodel: False
fold: 3
seed: 345
emb_dimension: 60
nepochs: 60
nhidden: 200
decay: True
lr: 0.0970806646813
folder: ../result
... loading the dataset
... building the model
... training
NEW BEST: epoch 0 valid F1 83.5 best test F1 79.27
NEW BEST: epoch 1 valid F1 86.97 best test F1 84.0
NEW BEST: epoch 2 valid F1 90.91 best test F1 88.52
NEW BEST: epoch 3 valid F1 92.24 best test F1 89.87
NEW BEST: epoch 4 valid F1 92.72 best test F1 89.9
NEW BEST: epoch 5 valid F1 94.19 best test F1 91.47

NEW BEST: epoch 7 valid F1 95.06 best test F1 93.11
NEW BEST: epoch 8 valid F1 95.31 best test F1 93.43

NEW BEST: epoch 10 valid F1 95.73 best test F1 93.52

NEW BEST: epoch 12 valid F1 96.22 best test F1 93.82




NEW BEST: epoch 17 valid F1 96.25 best test F1 94.08
NEW BEST: epoch 18 valid F1 96.59 best test F1 93.77






NEW BEST: epoch 25 valid F1 96.63 best test F1 93.76




NEW BEST: epoch 30 valid F1 96.69 best test F1 93.93

NEW BEST: epoch 32 valid F1 9

(<hw4_nn.RNNSLU_norm at 0x7f350faf6190>,
 {'labels2idx': {'B-aircraft_code': 0,
   'B-airline_code': 1,
   'B-airline_name': 2,
   'B-airport_code': 3,
   'B-airport_name': 4,
   'B-arrive_date.date_relative': 5,
   'B-arrive_date.day_name': 6,
   'B-arrive_date.day_number': 7,
   'B-arrive_date.month_name': 8,
   'B-arrive_date.today_relative': 9,
   'B-arrive_time.end_time': 10,
   'B-arrive_time.period_mod': 11,
   'B-arrive_time.period_of_day': 12,
   'B-arrive_time.start_time': 13,
   'B-arrive_time.time': 14,
   'B-arrive_time.time_relative': 15,
   'B-booking_class': 16,
   'B-city_name': 17,
   'B-class_type': 18,
   'B-compartment': 19,
   'B-connect': 20,
   'B-cost_relative': 21,
   'B-day_name': 22,
   'B-day_number': 23,
   'B-days_code': 24,
   'B-depart_date.date_relative': 25,
   'B-depart_date.day_name': 26,
   'B-depart_date.day_number': 27,
   'B-depart_date.month_name': 28,
   'B-depart_date.today_relative': 29,
   'B-depart_date.year': 30,
   'B-depart_time.end_tim

In this problem, use the best parameter setting **win=5, emb_dimension=50**. 
The **Best Result** obtained at ```epoch 34``` with validation accracy of ```96.81%``` and best test accracy of ```94.35%```.

Using normalization, we can find that the convergence speed is much faster than the result in part I. We can also find that the average accuracy is higher than part I, and the optimal result is ```94.35%```, which is slightly higher than the result ```94.2%``` in part I. Therefore, we can conclude that, normalization can improve the RNN performance both in convergence speed and optimal result.

#### Bullet 5: Observation on embedding pairs

**Step 1: **Run RNN to obtain word embeddings using code for part I.

In [1]:
from hw4a import test_rnnslu
rnn, dic = test_rnnslu(win=7, emb_dimension=50, nepochs=60, verbose=False)

Using gpu device 0: GRID K520 (CNMeM is disabled, cuDNN Version is too old. Update to v5, was 3007.)
/home/ubuntu/miniconda2/envs/theano/lib/python2.7/site-packages/theano/tensor/signal/downsample.py:6: UserWarning: downsample module has been moved to the theano.tensor.signal.pool module.
  "downsample module has been moved to the theano.tensor.signal.pool module.")


... loading the dataset
... building the model
... training
BEST RESULT: epoch 57 valid F1 97.23 best test F1 94.2 with the model ../result


**Step 2: **Store words and their embeddings.

In [5]:
idx2label = dict((k, v) for v, k in dic['labels2idx'].items())
idx2word = dict((k, v) for v, k in dic['words2idx'].items())
embeddings = rnn.emb.get_value()
print 'idx2label =\n', idx2label
print 'idx2word =\n', idx2word
print 'embeddings =\n', embeddings
print 'embeddings.shape =', embeddings.shape

idx2label =
{0: 'B-aircraft_code', 1: 'B-airline_code', 2: 'B-airline_name', 3: 'B-airport_code', 4: 'B-airport_name', 5: 'B-arrive_date.date_relative', 6: 'B-arrive_date.day_name', 7: 'B-arrive_date.day_number', 8: 'B-arrive_date.month_name', 9: 'B-arrive_date.today_relative', 10: 'B-arrive_time.end_time', 11: 'B-arrive_time.period_mod', 12: 'B-arrive_time.period_of_day', 13: 'B-arrive_time.start_time', 14: 'B-arrive_time.time', 15: 'B-arrive_time.time_relative', 16: 'B-booking_class', 17: 'B-city_name', 18: 'B-class_type', 19: 'B-compartment', 20: 'B-connect', 21: 'B-cost_relative', 22: 'B-day_name', 23: 'B-day_number', 24: 'B-days_code', 25: 'B-depart_date.date_relative', 26: 'B-depart_date.day_name', 27: 'B-depart_date.day_number', 28: 'B-depart_date.month_name', 29: 'B-depart_date.today_relative', 30: 'B-depart_date.year', 31: 'B-depart_time.end_time', 32: 'B-depart_time.period_mod', 33: 'B-depart_time.period_of_day', 34: 'B-depart_time.start_time', 35: 'B-depart_time.time', 36: '

**Step 3: **Link the words and their embeddings. Test one word 'about'.

In [8]:
word = {}
for idx, val in idx2word.iteritems():
    word[val] = embeddings[idx]
print word['about']

[-0.20508134 -0.14267085 -0.10787897 -0.04473343  0.16065724  0.22887182
  0.05090498 -0.03107767 -0.05584493 -0.19493052 -0.08219223 -0.10101879
  0.39483741  0.05841397 -0.1096677   0.11169763  0.02490725 -0.04589058
  0.23181684 -0.09582186  0.05386055 -0.23040548  0.10045996  0.12200679
  0.02672083  0.04181758  0.12818792  0.02886511  0.01482141  0.12816785
 -0.04433954 -0.2195625  -0.19592176 -0.02675461  0.14448406 -0.10090398
 -0.20413867  0.10212246  0.05561973 -0.00377944  0.00803433 -0.05416036
  0.16486469  0.22210068  0.2892364  -0.12799247  0.13997686 -0.13548465
  0.03341902 -0.15220492]


**Step 4: **Test cosine distance between words.

In [15]:
from scipy.spatial.distance import cosine
print cosine(word['pennsylvania'] - word['pittsburgh'], word['pennsylvania'] - word['philadelphia'])

0.300818201959


In [20]:
from scipy.spatial.distance import cosine
print cosine(word['washington'] - word['seattle'], word['pennsylvania'] - word['philadelphia'])

0.918675592444


In [21]:
from scipy.spatial.distance import cosine
print cosine(word['washington'] - word['seattle'], word['california'] - word['oakland'])

0.759945932385


In [22]:
from scipy.spatial.distance import cosine
print cosine(word['las'] - word['vegas'], word['new'] - word['york'])

0.440767916049


In [19]:
from scipy.spatial.distance import cosine
print cosine(word['united'] - word['airline'], word['american'] - word['airline'])

0.0545001540881


In [14]:
from scipy.spatial.distance import cosine
print cosine(word['united'] - word['reservation'], word['american'] - word['reservation'])

0.0525753339937


In [18]:
from scipy.spatial.distance import cosine
print cosine(word['city'] - word['cities'], word['class'] - word['classes'])

0.971108958153


In [23]:
from scipy.spatial.distance import cosine
print cosine(word['city'] - word['seattle'], word['city'] - word['oakland'])

0.339438291472


### Problem b: Learning Parity Function
#### Bullet 1: Shallow MLP

(1) For 8 bits input, it can obtain 100% test accuracy by using parameter of 

    learning_rate=0.1, n_epochs=2000, batch_size=20, n_hidden=16, n_hl=1.

In [1]:
from hw4b import test_mlp_parity
test_mlp_parity(learning_rate=0.1, n_epochs=2000, batch_size=20, n_hidden=16, n_hl=1, n_bit=8)

Using gpu device 0: GRID K520 (CNMeM is disabled, cuDNN Version is too old. Update to v5, was 3007.)
/home/ubuntu/miniconda2/envs/theano/lib/python2.7/site-packages/theano/tensor/signal/downsample.py:6: UserWarning: downsample module has been moved to the theano.tensor.signal.pool module.
  "downsample module has been moved to the theano.tensor.signal.pool module.")


... building the model
... training
Optimization complete.
Best validation score of 0.000000 % obtained at iteration 24400, with test performance 0.000000 %


The training process for function test_mlp_parity ran for 1.20m


(2) For 12 bits input, it can obtain 100% test accuracy by using parameter of 

    learning_rate=0.5, n_epochs=10000, batch_size=20, n_hidden=64, n_hl=1.

In [1]:
from hw4b import test_mlp_parity
test_mlp_parity(learning_rate=0.5, n_epochs=10000, batch_size=20, n_hidden=64, n_hl=1, n_bit=12)

Using gpu device 0: GRID K520 (CNMeM is disabled, cuDNN Version is too old. Update to v5, was 3007.)
/home/ubuntu/miniconda2/envs/theano/lib/python2.7/site-packages/theano/tensor/signal/downsample.py:6: UserWarning: downsample module has been moved to the theano.tensor.signal.pool module.
  "downsample module has been moved to the theano.tensor.signal.pool module.")


... building the model
... training
Optimization complete.
Best validation score of 3.600000 % obtained at iteration 90600, with test performance 0.000000 %


The training process for function test_mlp_parity ran for 6.12m


#### Bullet 2: Deep MLP

(1) For 8 bits input, it can obtain 100% test accuracy by using parameter of 

    learning_rate=0.1, n_epochs=2000, batch_size=20, n_hidden=16, n_hl=3.

In [3]:
from hw4b import test_mlp_parity
test_mlp_parity(learning_rate=0.1, n_epochs=2000, batch_size=20, n_hidden=16, n_hl=3, n_bit=8)

... building the model
... training
Optimization complete.
Best validation score of 0.000000 % obtained at iteration 10350, with test performance 0.000000 %


The training process for function test_mlp_parity ran for 1.87m


(2) For 12 bits input, it can obtain 100% test accuracy by using parameter of 

    learning_rate=0.8, n_epochs=10000, batch_size=20, n_hidden=128, n_hl=2.

In [3]:
from hw4b import test_mlp_parity
test_mlp_parity(learning_rate=0.8, n_epochs=10000, batch_size=20, n_hidden=128, n_hl=2, n_bit=12)

... building the model
... training
Optimization complete.
Best validation score of 0.400000 % obtained at iteration 246450, with test performance 0.000000 %


The training process for function test_mlp_parity ran for 7.43m


Comparing the parameter settings in part I and II, we can conclude the following points.

1. Deep MLP need more hidden units to obtain 100% accuracy.
+  Deep MLP need more epochs to obtain 100% accuracy.
+  It is more difficult to obtain 100% accuracy when the number of hidden layers grows.

#### Bullet 3: RNN

(1) For 8 bits input, it can obtain 100% test accuracy by using parameter of 

    learning_rate=0.1, n_epochs=100, n_hidden=4.

In [1]:
from hw4b import test_rnn_parity
test_rnn_parity(learning_rate=0.1, n_epochs=100, batch_size=20, n_hidden=4, verbose=True, n_bit=8)

Using gpu device 0: GRID K520 (CNMeM is disabled, cuDNN Version is too old. Update to v5, was 3007.)
/home/ubuntu/miniconda2/envs/theano/lib/python2.7/site-packages/theano/tensor/signal/downsample.py:6: UserWarning: downsample module has been moved to the theano.tensor.signal.pool module.
  "downsample module has been moved to the theano.tensor.signal.pool module.")


fold: 3
seed: 345
lr: 0.1
verbose: True
normal: True
decay: True
nhidden: 4
folder: ../result
savemodel: False
nepochs: 100
... building the model
... training
('NEW BEST: epoch', 0, 'valid F1', 51.799999999999997, 'best test F1', 49.0)
('NEW BEST: epoch', 1, 'valid F1', 51.799999999999997, 'best test F1', 49.0)
('NEW BEST: epoch', 2, 'valid F1', 51.799999999999997, 'best test F1', 49.0)
('NEW BEST: epoch', 3, 'valid F1', 51.799999999999997, 'best test F1', 49.0)
('NEW BEST: epoch', 4, 'valid F1', 51.799999999999997, 'best test F1', 49.0)
('NEW BEST: epoch', 5, 'valid F1', 51.799999999999997, 'best test F1', 51.0)
('NEW BEST: epoch', 6, 'valid F1', 46.399999999999999, 'best test F1', 46.0)
('NEW BEST: epoch', 7, 'valid F1', 49.799999999999997, 'best test F1', 56.0)
('NEW BEST: epoch', 8, 'valid F1', 48.799999999999997, 'best test F1', 53.0)
('NEW BEST: epoch', 9, 'valid F1', 48.799999999999997, 'best test F1', 53.0)
('NEW BEST: epoch', 10, 'valid F1', 48.799999999999997, 'best test F1'

(2) For 12 bits input, it can obtain 100% test accuracy by using parameter of 

    learning_rate=0.1, n_epochs=100, n_hidden=6.

In [3]:
from hw4b import test_rnn_parity
test_rnn_parity(learning_rate=0.1, n_epochs=100, batch_size=20, n_hidden=6, verbose=True, n_bit=12)

fold: 3
seed: 345
lr: 0.1
verbose: True
normal: True
decay: True
nhidden: 6
folder: ../result
savemodel: False
nepochs: 100
... building the model
... training
('NEW BEST: epoch', 0, 'valid F1', 54.0, 'best test F1', 46.0)
('NEW BEST: epoch', 1, 'valid F1', 54.0, 'best test F1', 46.0)
('NEW BEST: epoch', 2, 'valid F1', 54.0, 'best test F1', 46.0)
('NEW BEST: epoch', 3, 'valid F1', 54.0, 'best test F1', 46.0)
('NEW BEST: epoch', 4, 'valid F1', 54.0, 'best test F1', 46.0)
('NEW BEST: epoch', 5, 'valid F1', 54.0, 'best test F1', 46.0)
('NEW BEST: epoch', 6, 'valid F1', 54.0, 'best test F1', 46.0)
('NEW BEST: epoch', 7, 'valid F1', 54.0, 'best test F1', 46.0)
('NEW BEST: epoch', 8, 'valid F1', 54.0, 'best test F1', 46.0)
('NEW BEST: epoch', 9, 'valid F1', 54.200000000000003, 'best test F1', 46.0)
('NEW BEST: epoch', 10, 'valid F1', 54.200000000000003, 'best test F1', 46.0)
('NEW BEST: epoch', 11, 'valid F1', 54.200000000000003, 'best test F1', 46.0)
('NEW BEST: epoch', 12, 'valid F1', 54.2

We can find that using RNN it can obtain 100% accuracy even when the number of hidden units is very small (like 4 or 6). Therefore, RNN has better performance than 2-layer MLP and deep MLP.

#### Bullet 4: LSTM

In [1]:
from hw4b import test_lstm_parity
test_lstm_parity(learning_rate=0.1, n_epochs=10, n_hidden=1, verbose=True, n_bit=8)

Using gpu device 0: GRID K520 (CNMeM is disabled, cuDNN Version is too old. Update to v5, was 3007.)
/home/ubuntu/miniconda2/envs/theano/lib/python2.7/site-packages/theano/tensor/signal/downsample.py:6: UserWarning: downsample module has been moved to the theano.tensor.signal.pool module.
  "downsample module has been moved to the theano.tensor.signal.pool module.")


fold: 3
seed: 345
lr: 0.1
verbose: True
normal: True
decay: True
nhidden: 1
folder: ../result
savemodel: False
nepochs: 10
... building the model
... training
('NEW BEST: epoch', 0, 'valid F1', 47.399999999999999, 'best test F1', 53.0)
('NEW BEST: epoch', 1, 'valid F1', 50.200000000000003, 'best test F1', 55.0)
('NEW BEST: epoch', 2, 'valid F1', 50.200000000000003, 'best test F1', 55.0)
('NEW BEST: epoch', 3, 'valid F1', 51.399999999999999, 'best test F1', 59.0)
('NEW BEST: epoch', 4, 'valid F1', 100.0, 'best test F1', 100.0)
('NEW BEST: epoch', 5, 'valid F1', 100.0, 'best test F1', 100.0)
('NEW BEST: epoch', 6, 'valid F1', 100.0, 'best test F1', 100.0)
('NEW BEST: epoch', 7, 'valid F1', 100.0, 'best test F1', 100.0)
('NEW BEST: epoch', 8, 'valid F1', 100.0, 'best test F1', 100.0)
('NEW BEST: epoch', 9, 'valid F1', 100.0, 'best test F1', 100.0)
('BEST RESULT: epoch', 9, 'valid F1', 100.0, 'best test F1', 100.0)


In [2]:
from hw4b import test_lstm_parity
test_lstm_parity(learning_rate=0.1, n_epochs=10, n_hidden=1, verbose=True, n_bit=12)

fold: 3
seed: 345
lr: 0.1
verbose: True
normal: True
decay: True
nhidden: 1
folder: ../result
savemodel: False
nepochs: 10
... building the model
... training
('NEW BEST: epoch', 0, 'valid F1', 54.399999999999999, 'best test F1', 45.0)
('NEW BEST: epoch', 1, 'valid F1', 55.399999999999999, 'best test F1', 42.0)
('NEW BEST: epoch', 2, 'valid F1', 53.799999999999997, 'best test F1', 46.0)
('NEW BEST: epoch', 3, 'valid F1', 53.200000000000003, 'best test F1', 45.0)
('NEW BEST: epoch', 4, 'valid F1', 54.799999999999997, 'best test F1', 46.0)
('NEW BEST: epoch', 5, 'valid F1', 53.600000000000001, 'best test F1', 51.0)
('NEW BEST: epoch', 6, 'valid F1', 53.600000000000001, 'best test F1', 51.0)
('NEW BEST: epoch', 7, 'valid F1', 52.799999999999997, 'best test F1', 49.0)
('NEW BEST: epoch', 8, 'valid F1', 100.0, 'best test F1', 100.0)
('NEW BEST: epoch', 9, 'valid F1', 100.0, 'best test F1', 100.0)
('BEST RESULT: epoch', 9, 'valid F1', 100.0, 'best test F1', 100.0)


We can find that using LSTM it can obtain 100% accuracy even when the number of hidden units is 1. Therefore, LSTM has better performance than above three. What's more, LSTM has good convergency property. The accuracy grows to 100% just within 10 epochs.